classdef broadbandfit < handle
    properties
        lambda;
        rho;
        reference_spectrum;
        
        chromophore_bounds=struct;
        
    end
    properties(Hidden=true)
        ext_coef;
        k=.001;  % steepness of logistic models
        Q=[];
        R=[];
        P=[];
    end
    
    methods
        function obj = broadbandfit(lambda,rho,reference_spectrum)
            obj.lambda=lambda;
            obj.rho=rho;
            obj.reference_spectrum=reference_spectrum;
            obj.ext_coef=nirs.media.getspectra(lambda)*1E-6;
            
            obj.chromophore_bounds.hbo.expected = 50;
            obj.chromophore_bounds.hbo.estimated=obj.chromophore_bounds.hbo.expected;
            obj.chromophore_bounds.hbo.lower=10;
            obj.chromophore_bounds.hbo.upper=120;
            obj.chromophore_bounds.hbo.fit =true;
            
            obj.chromophore_bounds.hbr.expected = 30;
            obj.chromophore_bounds.hbr.estimated=obj.chromophore_bounds.hbr.expected;
            obj.chromophore_bounds.hbr.lower=10;
            obj.chromophore_bounds.hbr.upper=100;
            obj.chromophore_bounds.hbr.fit =true;
            
            obj.chromophore_bounds.water.expected = 0.85
            obj.chromophore_bounds.water.estimated=obj.chromophore_bounds.water.expected;
            obj.chromophore_bounds.water.lower=0.70
            obj.chromophore_bounds.water.upper=0.95;
            obj.chromophore_bounds.water.fit =true;
            
            obj.chromophore_bounds.cco.expected=.1;
            obj.chromophore_bounds.cco.estimated=obj.chromophore_bounds.cco.expected;
            obj.chromophore_bounds.cco.lower=0;
            obj.chromophore_bounds.cco.upper=1;
            obj.chromophore_bounds.cco.fit =true;
            
            
            obj.chromophore_bounds.a.expected=.01;
            obj.chromophore_bounds.a.estimated=obj.chromophore_bounds.a.expected;
            obj.chromophore_bounds.a.lower=0.001;
            obj.chromophore_bounds.a.upper=.02;
            obj.chromophore_bounds.a.fit =true;
            
            obj.chromophore_bounds.b.expected=1.5;
            obj.chromophore_bounds.b.estimated=obj.chromophore_bounds.b.expected;
            obj.chromophore_bounds.b.lower=1;
            obj.chromophore_bounds.b.upper=2;
            obj.chromophore_bounds.b.fit =true;
            
            
        end
        
        function obj=kalman_update(obj,y)
            
            W=obj.chromophore_bounds.water.estimated;
            hbo=obj.chromophore_bounds.hbo.estimated;
            hbr=obj.chromophore_bounds.hbr.estimated;
            cco=obj.chromophore_bounds.cco.estimated;
            a=obj.chromophore_bounds.a.estimated;
            b=obj.chromophore_bounds.b.estimated;
            
            
            
            x = obj.bound_all(W,hbo,hbr,cco,a,b);
            % Extended Kalman filter
            
                xhat = x;
                P = obj.P + obj.Q;
                res = y-obj.ref_est(W,hbo,hbr,cco,a,b);
                dy_dc = obj.d_ref_est(W,hbo,hbr,cco,a,b);
                dc_dx = obj.get_bounds_derivative(W,hbo,hbr,cco,a,b);
                J = dy_dc*dc_dx;
                s = J*P*J' + obj.R;
                K = P*J'*pinv(s);
                x = xhat + K*res;
                obj.P = (eye(6)-K*J)*P;
                [W,hbo,hbr,cco,a,b]=obj.unbound_all(x);
            
            obj.chromophore_bounds.water.estimated=W;
            obj.chromophore_bounds.hbo.estimated=hbo;
            obj.chromophore_bounds.hbr.estimated=hbr;
            obj.chromophore_bounds.cco.estimated=cco;
            obj.chromophore_bounds.a.estimated=a;
            obj.chromophore_bounds.b.estimated=b;
            
            
        end
        
        
        
        function obj=fit_spectrum_static(obj,y)
            
            W=obj.chromophore_bounds.water.estimated;
            hbo=obj.chromophore_bounds.hbo.estimated;
            hbr=obj.chromophore_bounds.hbr.estimated;
            cco=obj.chromophore_bounds.cco.estimated;
            a=obj.chromophore_bounds.a.estimated;
            b=obj.chromophore_bounds.b.estimated;
            
            x = obj.bound_all(W,hbo,hbr,cco,a,b);
            l=plot(obj.lambda,y,'b'); hold on;
            yhat = obj.ref_est(W,hbo,hbr,cco,a,b);
            l2=plot(obj.lambda,yhat,'r--');
            set(gca,'YScale','log');
            drawnow;
            lambda=.01;
            iter=0;
            mserror=inf;
            
            zeroPad=zeros(6,size(y,2));
            
            while(1)
                iter=iter+1;
                yhat = obj.ref_est(W,hbo,hbr,cco,a,b);
                set(l2,'ydata',yhat);
                drawnow;
                res = y-yhat*ones(1,size(y,2));
                dy_dc = obj.d_ref_est(W,hbo,hbr,cco,a,b);
                dc_dx = obj.get_bounds_derivative(W,hbo,hbr,cco,a,b);
                J = dy_dc*dc_dx;
                
                diagJacTJac=sum(J.^2,1)';
                scaleMat = diag(sqrt(lambda*diagJacTJac));
                
                AugJac = [J; scaleMat];
                AugRes = [res; zeroPad]; % Augmented residual
                
                dx = AugJac \ AugRes; 
                
                if(mod(iter,10)==0);
                    lambda=lambda*2;
                end;
                
                x=x+nanmedian(dx,2);
                x=sign(x).*nanmin(abs(x),1e4);
                newmse=mse(res(:));
                
                
                disp(['iteration-' num2str(iter) ' MSE-change % ' num2str(100*(mserror-newmse)/mserror)]);
                [W,hbo,hbr,cco,a,b]=obj.unbound_all(x);
                
                 if(abs(mserror-newmse)<1E-8)
                     break;
                 end

                mserror=newmse;
            end
            
            % set up the kalman estimater
            obj.Q=eye(6);
            obj.R=cov(res');
            obj.P=J'*obj.R*J;
            
            
            obj.chromophore_bounds.water.estimated=W;
            obj.chromophore_bounds.hbo.estimated=hbo;
            obj.chromophore_bounds.hbr.estimated=hbr;
            obj.chromophore_bounds.cco.estimated=cco;
            obj.chromophore_bounds.a.estimated=a;
            obj.chromophore_bounds.b.estimated=b;
            
            
        end
        
        
        
        
        
        function yhat = ref_est(obj,W,hbo,hbr,cco,a,b)
            lambda=obj.lambda;
            c0=obj.ext_coef(:,1);
            c1=obj.ext_coef(:,2);
            c2=obj.ext_coef(:,3);
            c3=obj.ext_coef(:,4);
            rho=obj.rho;
            r=obj.reference_spectrum;
            
            yhat=r./(25000.*pi.*((exp(-3.^(1./2).*(1./(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr +...
                a./lambda.^b).^2 + rho.^2).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo +...
                c2.*hbr).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr +...
                a./lambda.^b).^(1./2)).*(1./(1./(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr...
                + a./lambda.^b).^2 + rho.^2).^(1./2) + 3.^(1./2).*(W.*c0 + c3.*cco + c1.*hbo...
                + c2.*hbr).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr +...
                a./lambda.^b).^(1./2)))./((1./(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr +...
                a./lambda.^b).^2 + rho.^2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr +...
                a./lambda.^b)) + (7493.*lambda.^b.*exp(-3.^(1./2).*((56145049.*lambda.^(2.*b))./(2313441.*(a +...
                W.*c0.*lambda.^b + c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b).^2) +...
                rho.^2).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr).^(1./2).*(W.*c0 + c3.*cco +...
                c1.*hbo + c2.*hbr + a./lambda.^b).^(1./2)).*(1./((56145049.*lambda.^(2.*b))./(2313441.*(a +...
                W.*c0.*lambda.^b + c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b).^2) +...
                rho.^2).^(1./2) + 3.^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr).^(1./2).*(W.*c0 +...
                c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^(1./2)))./(1521.*((56145049.*lambda.^(2.*b))./(2313441.*(a +...
                W.*c0.*lambda.^b + c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b).^2) +...
                rho.^2).*(a + W.*c0.*lambda.^b + c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b))));
            
        end
        
        function x = bound_all(obj,W,hbo,hbr,cco,a,b)
            x=zeros(6,1);
            x(1)=obj.bound(W,'water');
            x(2)=obj.bound(hbo,'hbo');
            x(3)=obj.bound(hbr,'hbr');
            x(4)=obj.bound(cco,'cco');
            x(5)=obj.bound(a,'a');
            x(6)=obj.bound(b,'b');
        end
        
        function [W,hbo,hbr,cco,a,b]=unbound_all(obj,x)
            W=  obj.unbound(x(1),'water');
            hbo=obj.unbound(x(2),'hbo');
            hbr=obj.unbound(x(3),'hbr');
            cco=obj.unbound(x(4),'cco');
            a  =obj.unbound(x(5),'a');
            b=  obj.unbound(x(6),'b');
        end
        
        
        function dc_dx = get_bounds_derivative(obj,W,hbo,hbr,cco,a,b)
            
            dc_dx=eye(6);
            dc_dx(1,1)=obj.unbound_derivative(W,'water',true);
            dc_dx(2,2)=obj.unbound_derivative(hbo,'hbo',true);
            dc_dx(3,3)=obj.unbound_derivative(hbr,'hbr',true);
            dc_dx(4,4)=obj.unbound_derivative(cco,'cco',true);
            dc_dx(5,5)=obj.unbound_derivative(a,'a',true);
            dc_dx(6,6)=obj.unbound_derivative(b,'b',true);
            
            
        end
        
        function dc_dx = unbound_derivative(obj,x,name,bound)
            
            if(nargin>3 && bound==true)
                x = obj.bound(x,name);
            end
            
            if(obj.chromophore_bounds.(name).fit)
                expected=obj.chromophore_bounds.(name).expected;
                upper=obj.chromophore_bounds.(name).upper;
                dc_dx=(upper*obj.k*exp(-obj.k*(x - expected)))/(exp(-obj.k*(x - expected)) + 1)^2;
            else
                dc_dx=0;
            end
            
        end
        function c = unbound(obj,x,name)
            
            expected=obj.chromophore_bounds.(name).expected;
            lower=obj.chromophore_bounds.(name).lower;
            upper=obj.chromophore_bounds.(name).upper;
            c = lower + upper/(1+exp(-obj.k*(x-expected)));
            
        end
        
        
        function x = bound(obj,c,name)
            
            if(c<=0)
                warning('chromophore must be positive');
                c=eps(1);
            end
            
            expected=obj.chromophore_bounds.(name).expected;
            lower=obj.chromophore_bounds.(name).lower;
            upper=obj.chromophore_bounds.(name).upper;
            x=-log(upper/(c-lower)-1)/obj.k+expected;
            
        end
        
        
        function dy_dc = d_ref_est(obj,W,hbo,hbr,cco,a,b)
            c0=obj.ext_coef(:,1);
            c1=obj.ext_coef(:,2);
            c2=obj.ext_coef(:,3);
            c3=obj.ext_coef(:,4);
            
            
            dy_dW  =obj.dconc_ref_est(c0,W,c1,hbo,c2,hbr,c3,cco,a,b);
            dy_dhbo=obj.dconc_ref_est(c1,hbo,c0,W,c2,hbr,c3,cco,a,b);
            dy_dhbr=obj.dconc_ref_est(c2,hbr,c0,W,c1,hbo,c3,cco,a,b);
            dy_dcco=obj.dconc_ref_est(c3,cco,c0,W,c1,hbo,c2,hbr,a,b);
            dy_da  =obj.da_ref_est(W,hbo,hbr,cco,a,b);
            dy_db  =obj.db_ref_est(W,hbo,hbr,cco,a,b);
            
            dy_dc=[dy_dW dy_dhbo dy_dhbr dy_dcco dy_da dy_db];
            
        end
        function dy_db=db_ref_est(obj,W,hbo,hbr,cco,a,b)
            lambda=obj.lambda;
            c0=obj.ext_coef(:,1);
            c1=obj.ext_coef(:,2);
            c2=obj.ext_coef(:,3);
            c3=obj.ext_coef(:,4);
            rho=obj.rho;
            r=obj.reference_spectrum;
            
            dy_db=(r.*((exp(-3.^(1./2).*(1./(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^2 +...
                rho.^2).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr).^(1./2).*(W.*c0 + c3.*cco +...
                c1.*hbo + c2.*hbr + a./lambda.^b).^(1./2)).*((a.*log(lambda))./(lambda.^b.*(1./(W.*c0 +...
                c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^2 + rho.^2).^(3./2).*(W.*c0 + c3.*cco +...
                c1.*hbo + c2.*hbr + a./lambda.^b).^3) + (3.^(1./2).*a.*log(lambda).*(W.*c0 + c3.*cco +...
                c1.*hbo + c2.*hbr).^(1./2))./(2.*lambda.^b.*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr +...
                a./lambda.^b).^(1./2))))./((1./(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^2 +...
                rho.^2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b)) +...
                (7493.*lambda.^b.*exp(-3.^(1./2).*((56145049.*lambda.^(2.*b))./(2313441.*(a +...
                W.*c0.*lambda.^b + c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b).^2) +...
                rho.^2).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo +...
                c2.*hbr + a./lambda.^b).^(1./2)).*(((112290098.*lambda.^(2.*b).*log(lambda))./(2313441.*(a +...
                W.*c0.*lambda.^b + c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b).^2) -...
                (112290098.*lambda.^(2.*b).*(W.*c0.*lambda.^b.*log(lambda) + c3.*cco.*lambda.^b.*log(lambda) +...
                c1.*hbo.*lambda.^b.*log(lambda) + c2.*hbr.*lambda.^b.*log(lambda)))./(2313441.*(a +...
                W.*c0.*lambda.^b + c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b +...
                c2.*hbr.*lambda.^b).^3))./(2.*((56145049.*lambda.^(2.*b))./(2313441.*(a + W.*c0.*lambda.^b +...
                c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b).^2) + rho.^2).^(3./2)) +...
                (3.^(1./2).*a.*log(lambda).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr).^(1./2))./(2.*lambda.^b.*(W.*c0 +...
                c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^(1./2))))./(1521.*((56145049.*lambda.^(2.*b))./(2313441.*(a +...
                W.*c0.*lambda.^b + c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b).^2) + rho.^2).*(a +...
                W.*c0.*lambda.^b + c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b)) -...
                (exp(-3.^(1./2).*(1./(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^2 + rho.^2).^(1./2).*(W.*c0 +...
                c3.*cco + c1.*hbo + c2.*hbr).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^(1./2)).*(1./(1./(W.*c0 + ...
                c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^2 + rho.^2).^(1./2) + 3.^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + ...
                c2.*hbr).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^(1./2)).*((3.^(1./2).*a.*log(lambda).*(1./(W.*c0 +...
                c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^2 + rho.^2).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + ...
                c2.*hbr).^(1./2))./(2.*lambda.^b.*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^(1./2)) - ...
                (3.^(1./2).*a.*log(lambda).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr).^(1./2))./(lambda.^b.*(1./(W.*c0 + c3.*cco + ...
                c1.*hbo + c2.*hbr + a./lambda.^b).^2 + rho.^2).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr +...
                a./lambda.^b).^(5./2))))./((1./(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^2 + rho.^2).*(W.*c0 +...
                c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b)) + (7493.*lambda.^b.*exp(-3.^(1./2).*((56145049.*lambda.^(2.*b))./(2313441.*(a +...
                W.*c0.*lambda.^b + c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b).^2) + rho.^2).^(1./2).*(W.*c0 + ...
                c3.*cco + c1.*hbo + c2.*hbr).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr +...
                a./lambda.^b).^(1./2)).*(1./((56145049.*lambda.^(2.*b))./(2313441.*(a + W.*c0.*lambda.^b + c3.*cco.*lambda.^b + ...
                c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b).^2) + rho.^2).^(1./2) + 3.^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + ...
                c2.*hbr).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^(1./2)).*((3.^(1./2).*((112290098.*lambda.^(2.*b).*log(lambda))./(2313441.*(a + ...
                W.*c0.*lambda.^b + c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b).^2) -...
                (112290098.*lambda.^(2.*b).*(W.*c0.*lambda.^b.*log(lambda) + c3.*cco.*lambda.^b.*log(lambda) + c1.*hbo.*lambda.^b.*log(lambda) +...
                c2.*hbr.*lambda.^b.*log(lambda)))./(2313441.*(a + W.*c0.*lambda.^b + c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b + ...
                c2.*hbr.*lambda.^b).^3)).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr + ...
                a./lambda.^b).^(1./2))./(2.*((56145049.*lambda.^(2.*b))./(2313441.*(a + W.*c0.*lambda.^b + c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b +...
                c2.*hbr.*lambda.^b).^2) + rho.^2).^(1./2)) - (3.^(1./2).*a.*log(lambda).*((56145049.*lambda.^(2.*b))./(2313441.*(a + W.*c0.*lambda.^b +...
                c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b).^2) + rho.^2).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo +...
                c2.*hbr).^(1./2))./(2.*lambda.^b.*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^(1./2))))./(1521.*((56145049.*lambda.^(2.*b))./(2313441.*(a + ...
                W.*c0.*lambda.^b + c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b).^2) + rho.^2).*(a + W.*c0.*lambda.^b + c3.*cco.*lambda.^b +...
                c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b)) - (7493.*lambda.^b.*exp(-3.^(1./2).*((56145049.*lambda.^(2.*b))./(2313441.*(a +...
                W.*c0.*lambda.^b + c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b).^2) + rho.^2).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo +...
                c2.*hbr).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^(1./2)).*log(lambda).*(1./((56145049.*lambda.^(2.*b))./(2313441.*(a +...
                W.*c0.*lambda.^b + c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b).^2) + rho.^2).^(1./2) + 3.^(1./2).*(W.*c0 + c3.*cco + c1.*hbo +...
                c2.*hbr).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^(1./2)))./(1521.*((56145049.*lambda.^(2.*b))./(2313441.*(a +...
                W.*c0.*lambda.^b + c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b).^2) + rho.^2).*(a + W.*c0.*lambda.^b + c3.*cco.*lambda.^b +...
                c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b)) + (7493.*lambda.^b.*exp(-3.^(1./2).*((56145049.*lambda.^(2.*b))./(2313441.*(a + W.*c0.*lambda.^b +...
                c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b).^2) + rho.^2).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr).^(1./2).*(W.*c0 +...
                c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^(1./2)).*(1./((56145049.*lambda.^(2.*b))./(2313441.*(a + W.*c0.*lambda.^b + c3.*cco.*lambda.^b +...
                c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b).^2) + rho.^2).^(1./2) + 3.^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr).^(1./2).*(W.*c0 + c3.*cco +...
                c1.*hbo + c2.*hbr + a./lambda.^b).^(1./2)).*((112290098.*lambda.^(2.*b).*log(lambda))./(2313441.*(a + W.*c0.*lambda.^b + c3.*cco.*lambda.^b +...
                c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b).^2) - (112290098.*lambda.^(2.*b).*(W.*c0.*lambda.^b.*log(lambda) + c3.*cco.*lambda.^b.*log(lambda) +...
                c1.*hbo.*lambda.^b.*log(lambda) + c2.*hbr.*lambda.^b.*log(lambda)))./(2313441.*(a + W.*c0.*lambda.^b + c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b +...
                c2.*hbr.*lambda.^b).^3)))./(1521.*((56145049.*lambda.^(2.*b))./(2313441.*(a + W.*c0.*lambda.^b + c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b +...
                c2.*hbr.*lambda.^b).^2) + rho.^2).^2.*(a + W.*c0.*lambda.^b + c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b)) +...
                (7493.*lambda.^b.*exp(-3.^(1./2).*((56145049.*lambda.^(2.*b))./(2313441.*(a + W.*c0.*lambda.^b + c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b +...
                c2.*hbr.*lambda.^b).^2) + rho.^2).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr +...
                a./lambda.^b).^(1./2)).*(1./((56145049.*lambda.^(2.*b))./(2313441.*(a + W.*c0.*lambda.^b + c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b +...
                c2.*hbr.*lambda.^b).^2) + rho.^2).^(1./2) + 3.^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo +...
                c2.*hbr + a./lambda.^b).^(1./2)).*(W.*c0.*lambda.^b.*log(lambda) + c3.*cco.*lambda.^b.*log(lambda) + c1.*hbo.*lambda.^b.*log(lambda) +...
                c2.*hbr.*lambda.^b.*log(lambda)))./(1521.*((56145049.*lambda.^(2.*b))./(2313441.*(a + W.*c0.*lambda.^b + c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b +...
                c2.*hbr.*lambda.^b).^2) + rho.^2).*(a + W.*c0.*lambda.^b + c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b).^2) -...
                (a.*exp(-3.^(1./2).*(1./(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^2 + rho.^2).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo +...
                c2.*hbr).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^(1./2)).*log(lambda).*(1./(1./(W.*c0 + c3.*cco + c1.*hbo +...
                c2.*hbr + a./lambda.^b).^2 + rho.^2).^(1./2) + 3.^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo +...
                c2.*hbr + a./lambda.^b).^(1./2)))./(lambda.^b.*(1./(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^2 +...
                rho.^2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^2) + (2.*a.*exp(-3.^(1./2).*(1./(W.*c0 + ...
                c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^2 + rho.^2).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr).^(1./2).*(W.*c0 +...
                c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^(1./2)).*log(lambda).*(1./(1./(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr +...
                a./lambda.^b).^2 + rho.^2).^(1./2) + 3.^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr).^(1./2).*(W.*c0 + c3.*cco +...
                c1.*hbo + c2.*hbr + a./lambda.^b).^(1./2)))./(lambda.^b.*(1./(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^2 +...
                rho.^2).^2.*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^4)))./(25000.*pi.*((exp(-3.^(1./2).*(1./(W.*c0 + ...
                c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^2 + rho.^2).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr).^(1./2).*(W.*c0 +...
                c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^(1./2)).*(1./(1./(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr +...
                a./lambda.^b).^2 + rho.^2).^(1./2) + 3.^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr).^(1./2).*(W.*c0 + ...
                c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^(1./2)))./((1./(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^2 +...
                rho.^2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b)) +...
                (7493.*lambda.^b.*exp(-3.^(1./2).*((56145049.*lambda.^(2.*b))./(2313441.*(a + W.*c0.*lambda.^b +...
                c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b).^2) + rho.^2).^(1./2).*(W.*c0 + c3.*cco +...
                c1.*hbo + c2.*hbr).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr + ...
                a./lambda.^b).^(1./2)).*(1./((56145049.*lambda.^(2.*b))./(2313441.*(a + W.*c0.*lambda.^b + c3.*cco.*lambda.^b +...
                c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b).^2) + rho.^2).^(1./2) + 3.^(1./2).*(W.*c0 + c3.*cco + c1.*hbo +...
                c2.*hbr).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr + ...
                a./lambda.^b).^(1./2)))./(1521.*((56145049.*lambda.^(2.*b))./(2313441.*(a + W.*c0.*lambda.^b + c3.*cco.*lambda.^b +...
                c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b).^2) + rho.^2).*(a + W.*c0.*lambda.^b + c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b))).^2);
            
        end
        function dy_da = da_ref_est(obj,W,hbo,hbr,cco,a,b)
            lambda=obj.lambda;
            c0=obj.ext_coef(:,1);
            c1=obj.ext_coef(:,2);
            c2=obj.ext_coef(:,3);
            c3=obj.ext_coef(:,4);
            rho=obj.rho;
            r=obj.reference_spectrum;
            dy_da=-(r.*((exp(-3.^(1./2).*(1./(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^2 +...
                rho.^2).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo +...
                c2.*hbr + a./lambda.^b).^(1./2)).*(1./(lambda.^b.*(1./(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr +...
                a./lambda.^b).^2 + rho.^2).^(3./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^3) +...
                (3.^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr).^(1./2))./(2.*lambda.^b.*(W.*c0 + c3.*cco +...
                c1.*hbo + c2.*hbr + a./lambda.^b).^(1./2))))./((1./(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr +...
                a./lambda.^b).^2 + rho.^2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b)) - (exp(-3.^(1./2).*(1./(W.*c0 +...
                c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^2 + rho.^2).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo +...
                c2.*hbr).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^(1./2)).*(1./(1./(W.*c0 +...
                c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^2 + rho.^2).^(1./2) + 3.^(1./2).*(W.*c0 + c3.*cco +...
                c1.*hbo + c2.*hbr).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^(1./2)).*((3.^(1./2).*(1./(W.*c0 +...
                c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^2 + rho.^2).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo +...
                c2.*hbr).^(1./2))./(2.*lambda.^b.*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^(1./2)) -...
                (3.^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr).^(1./2))./(lambda.^b.*(1./(W.*c0 + c3.*cco + c1.*hbo +...
                c2.*hbr + a./lambda.^b).^2 + rho.^2).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr +...
                a./lambda.^b).^(5./2))))./((1./(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^2 + rho.^2).*(W.*c0 +...
                c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b)) +...
                (841389704314.*lambda.^(3.*b).*exp(-3.^(1./2).*((56145049.*lambda.^(2.*b))./(2313441.*(a + W.*c0.*lambda.^b +...
                c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b).^2) + rho.^2).^(1./2).*(W.*c0 + c3.*cco +...
                c1.*hbo + c2.*hbr).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr +...
                a./lambda.^b).^(1./2)).*(1./((56145049.*lambda.^(2.*b))./(2313441.*(a + W.*c0.*lambda.^b + c3.*cco.*lambda.^b +...
                c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b).^2) + rho.^2).^(1./2) + 3.^(1./2).*(W.*c0 + c3.*cco + c1.*hbo +...
                c2.*hbr).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^(1./2)))./(3518743761.*((56145049.*lambda.^(2.*b))./(2313441.*(a +...
                W.*c0.*lambda.^b + c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b).^2) + rho.^2).^2.*(a + ...
                W.*c0.*lambda.^b + c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b).^4) - (exp(-3.^(1./2).*(1./(W.*c0 +...
                c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^2 + rho.^2).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo +...
                c2.*hbr).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^(1./2)).*(1./(1./(W.*c0 +...
                c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^2 + rho.^2).^(1./2) + 3.^(1./2).*(W.*c0 + c3.*cco + ...
                c1.*hbo + c2.*hbr).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^(1./2)))./(lambda.^b.*(1./(W.*c0 +...
                c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^2 + rho.^2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^2) +...
                (2.*exp(-3.^(1./2).*(1./(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^2 + rho.^2).^(1./2).*(W.*c0 +...
                c3.*cco + c1.*hbo + c2.*hbr).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^(1./2)).*(1./(1./(W.*c0 +...
                c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^2 + rho.^2).^(1./2) + 3.^(1./2).*(W.*c0 + c3.*cco + c1.*hbo +...
                c2.*hbr).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^(1./2)))./(lambda.^b.*(1./(W.*c0 +...
                c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^2 + rho.^2).^2.*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr +...
                a./lambda.^b).^4) + (7493.*lambda.^b.*exp(-3.^(1./2).*((56145049.*lambda.^(2.*b))./(2313441.*(a + ...
                W.*c0.*lambda.^b + c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b).^2) + rho.^2).^(1./2).*(W.*c0 +...
                c3.*cco + c1.*hbo + c2.*hbr).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr +...
                a./lambda.^b).^(1./2)).*((56145049.*lambda.^(2.*b))./(2313441.*((56145049.*lambda.^(2.*b))./(2313441.*(a +...
                W.*c0.*lambda.^b + c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b).^2) + rho.^2).^(3./2).*(a +...
                W.*c0.*lambda.^b + c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b).^3) + (3.^(1./2).*(W.*c0 +...
                c3.*cco + c1.*hbo + c2.*hbr).^(1./2))./(2.*lambda.^b.*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr +...
                a./lambda.^b).^(1./2))))./(1521.*((56145049.*lambda.^(2.*b))./(2313441.*(a + W.*c0.*lambda.^b +...
                c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b).^2) + rho.^2).*(a + W.*c0.*lambda.^b +...
                c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b)) -...
                (7493.*lambda.^b.*exp(-3.^(1./2).*((56145049.*lambda.^(2.*b))./(2313441.*(a + W.*c0.*lambda.^b +...
                c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b).^2) + rho.^2).^(1./2).*(W.*c0 + c3.*cco +...
                c1.*hbo + c2.*hbr).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr + ...
                a./lambda.^b).^(1./2)).*(1./((56145049.*lambda.^(2.*b))./(2313441.*(a + W.*c0.*lambda.^b + c3.*cco.*lambda.^b +...
                c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b).^2) + rho.^2).^(1./2) + 3.^(1./2).*(W.*c0 + c3.*cco + c1.*hbo +...
                c2.*hbr).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^(1./2)))./(1521.*((56145049.*lambda.^(2.*b))./(2313441.*(a +...
                W.*c0.*lambda.^b + c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b).^2) + rho.^2).*(a + W.*c0.*lambda.^b +...
                c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b).^2) - (7493.*lambda.^b.*exp(-3.^(1./2).*((56145049.*lambda.^(2.*b))./(2313441.*(a +...
                W.*c0.*lambda.^b + c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b).^2) + rho.^2).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo +...
                c2.*hbr).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^(1./2)).*(1./((56145049.*lambda.^(2.*b))./(2313441.*(a +...
                W.*c0.*lambda.^b + c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b).^2) + rho.^2).^(1./2) + 3.^(1./2).*(W.*c0 + c3.*cco +...
                c1.*hbo + c2.*hbr).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^(1./2)).*((3.^(1./2).*((56145049.*lambda.^(2.*b))./(2313441.*(a + ...
                W.*c0.*lambda.^b + c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b).^2) + rho.^2).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + ...
                c2.*hbr).^(1./2))./(2.*lambda.^b.*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^(1./2)) - (56145049.*3.^(1./2).*lambda.^(2.*b).*(W.*c0 +...
                c3.*cco + c1.*hbo + c2.*hbr).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr + ...
                a./lambda.^b).^(1./2))./(2313441.*((56145049.*lambda.^(2.*b))./(2313441.*(a + W.*c0.*lambda.^b + c3.*cco.*lambda.^b +...
                c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b).^2) + rho.^2).^(1./2).*(a + W.*c0.*lambda.^b + c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b +...
                c2.*hbr.*lambda.^b).^3)))./(1521.*((56145049.*lambda.^(2.*b))./(2313441.*(a + W.*c0.*lambda.^b + c3.*cco.*lambda.^b +...
                c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b).^2) + rho.^2).*(a + W.*c0.*lambda.^b + c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b +...
                c2.*hbr.*lambda.^b))))./(25000.*pi.*((exp(-3.^(1./2).*(1./(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^2 +...
                rho.^2).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr +...
                a./lambda.^b).^(1./2)).*(1./(1./(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^2 + rho.^2).^(1./2) + 3.^(1./2).*(W.*c0 +...
                c3.*cco + c1.*hbo + c2.*hbr).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^(1./2)))./((1./(W.*c0 + c3.*cco +...
                c1.*hbo + c2.*hbr + a./lambda.^b).^2 + rho.^2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b)) +...
                (7493.*lambda.^b.*exp(-3.^(1./2).*((56145049.*lambda.^(2.*b))./(2313441.*(a + W.*c0.*lambda.^b + c3.*cco.*lambda.^b +...
                c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b).^2) + rho.^2).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr).^(1./2).*(W.*c0 +...
                c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^(1./2)).*(1./((56145049.*lambda.^(2.*b))./(2313441.*(a + W.*c0.*lambda.^b +...
                c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b).^2) + rho.^2).^(1./2) + 3.^(1./2).*(W.*c0 + c3.*cco + c1.*hbo +...
                c2.*hbr).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^(1./2)))./(1521.*((56145049.*lambda.^(2.*b))./(2313441.*(a +...
                W.*c0.*lambda.^b + c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b).^2) + rho.^2).*(a + W.*c0.*lambda.^b +...
                c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b))).^2);
            
        end
        
        function dy_dconc = dconc_ref_est(obj,c0,W,c1,hbo,c2,hbr,c3,cco,a,b)
            lambda=obj.lambda;
            rho=obj.rho;
            r=obj.reference_spectrum;
            
            dy_dconc=-(r.*((exp(-3.^(1./2).*(1./(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^2 +...
                rho.^2).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr).^(1./2).*(W.*c0 + c3.*cco +...
                c1.*hbo + c2.*hbr + a./lambda.^b).^(1./2)).*(c1./((1./(W.*c0 + c3.*cco + c1.*hbo +...
                c2.*hbr + a./lambda.^b).^2 + rho.^2).^(3./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr +...
                a./lambda.^b).^3) + (3.^(1./2).*c1.*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr +...
                a./lambda.^b).^(1./2))./(2.*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr).^(1./2)) +...
                (3.^(1./2).*c1.*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr).^(1./2))./(2.*(W.*c0 + c3.*cco +...
                c1.*hbo + c2.*hbr + a./lambda.^b).^(1./2))))./((1./(W.*c0 + c3.*cco + c1.*hbo +...
                c2.*hbr + a./lambda.^b).^2 + rho.^2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr +...
                a./lambda.^b)) + (7493.*lambda.^b.*exp(-3.^(1./2).*((56145049.*lambda.^(2.*b))./(2313441.*(a +...
                W.*c0.*lambda.^b + c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b).^2) +...
                rho.^2).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo +....
                c2.*hbr + a./lambda.^b).^(1./2)).*((3.^(1./2).*c1.*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr +...
                a./lambda.^b).^(1./2))./(2.*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr).^(1./2)) +...
                (3.^(1./2).*c1.*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr).^(1./2))./(2.*(W.*c0 + c3.*cco +...
                c1.*hbo + c2.*hbr + a./lambda.^b).^(1./2)) +...
                (56145049.*c1.*lambda.^(3.*b))./(2313441.*((56145049.*lambda.^(2.*b))./(2313441.*(a +...
                W.*c0.*lambda.^b + c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b).^2) + ...
                rho.^2).^(3./2).*(a + W.*c0.*lambda.^b + c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b + ...
                c2.*hbr.*lambda.^b).^3)))./(1521.*((56145049.*lambda.^(2.*b))./(2313441.*(a +...
                W.*c0.*lambda.^b + c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b).^2) +...
                rho.^2).*(a + W.*c0.*lambda.^b + c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b + ...
                c2.*hbr.*lambda.^b)) - (c1.*exp(-3.^(1./2).*(1./(W.*c0 + c3.*cco + c1.*hbo + ...
                c2.*hbr + a./lambda.^b).^2 + rho.^2).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + ...
                c2.*hbr).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^(1./2)).*(1./(1./(W.*c0 +...
                c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^2 + rho.^2).^(1./2) + 3.^(1./2).*(W.*c0 + ...
                c3.*cco + c1.*hbo + c2.*hbr).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr +...
                a./lambda.^b).^(1./2)))./((1./(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^2 +...
                rho.^2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^2) +...
                (2.*c1.*exp(-3.^(1./2).*(1./(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^2 +...
                rho.^2).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr).^(1./2).*(W.*c0 + c3.*cco +...
                c1.*hbo + c2.*hbr + a./lambda.^b).^(1./2)).*(1./(1./(W.*c0 + c3.*cco + c1.*hbo +...
                c2.*hbr + a./lambda.^b).^2 + rho.^2).^(1./2) + 3.^(1./2).*(W.*c0 + c3.*cco +...
                c1.*hbo + c2.*hbr).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr +...
                a./lambda.^b).^(1./2)))./((1./(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr +...
                a./lambda.^b).^2 + rho.^2).^2.*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr +...
                a./lambda.^b).^4) - (exp(-3.^(1./2).*(1./(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr +...
                a./lambda.^b).^2 + rho.^2).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr).^(1./2).*(W.*c0 + ...
                c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^(1./2)).*(1./(1./(W.*c0 + ...
                c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^2 + rho.^2).^(1./2) +...
                3.^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr).^(1./2).*(W.*c0 + c3.*cco + ...
                c1.*hbo + c2.*hbr + a./lambda.^b).^(1./2)).*((3.^(1./2).*c1.*(1./(W.*c0 + ...
                c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^2 + rho.^2).^(1./2).*(W.*c0 +...
                c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^(1./2))./(2.*(W.*c0 + c3.*cco +...
                c1.*hbo + c2.*hbr).^(1./2)) + (3.^(1./2).*c1.*(1./(W.*c0 + c3.*cco + c1.*hbo + ...
                c2.*hbr + a./lambda.^b).^2 + rho.^2).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo +...
                c2.*hbr).^(1./2))./(2.*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^(1./2)) - ...
                (3.^(1./2).*c1.*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr).^(1./2))./((1./(W.*c0 + ...
                c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^2 + rho.^2).^(1./2).*(W.*c0 + ...
                c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^(5./2))))./((1./(W.*c0 + c3.*cco + ...
                c1.*hbo + c2.*hbr + a./lambda.^b).^2 + rho.^2).*(W.*c0 + c3.*cco + c1.*hbo + ...
                c2.*hbr + a./lambda.^b)) - (7493.*lambda.^b.*exp(-3.^(1./2).*((56145049.*lambda.^(2.*b))./(2313441.*(a + ...
                W.*c0.*lambda.^b + c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b).^2) + ...
                rho.^2).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo +...
                c2.*hbr + a./lambda.^b).^(1./2)).*(1./((56145049.*lambda.^(2.*b))./(2313441.*(a +...
                W.*c0.*lambda.^b + c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b).^2) +...
                rho.^2).^(1./2) + 3.^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr).^(1./2).*(W.*c0 + ...
                c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^(1./2)).*((3.^(1./2).*c1.*((56145049.*lambda.^(2.*b))./(2313441.*(a +...
                W.*c0.*lambda.^b + c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b).^2) +...
                rho.^2).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^(1./2))./(2.*(W.*c0 + ...
                c3.*cco + c1.*hbo + c2.*hbr).^(1./2)) + (3.^(1./2).*c1.*((56145049.*lambda.^(2.*b))./(2313441.*(a + ...
                W.*c0.*lambda.^b + c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b).^2) + ...
                rho.^2).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr).^(1./2))./(2.*(W.*c0 + c3.*cco + c1.*hbo + ...
                c2.*hbr + a./lambda.^b).^(1./2)) - (56145049.*3.^(1./2).*c1.*lambda.^(3.*b).*(W.*c0 + c3.*cco + ...
                c1.*hbo + c2.*hbr).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr + ...
                a./lambda.^b).^(1./2))./(2313441.*((56145049.*lambda.^(2.*b))./(2313441.*(a + W.*c0.*lambda.^b +...
                c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b).^2) + rho.^2).^(1./2).*(a + W.*c0.*lambda.^b +...
                c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b).^3)))./(1521.*((56145049.*lambda.^(2.*b))./(2313441.*(a +...
                W.*c0.*lambda.^b + c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b).^2) + rho.^2).*(a + W.*c0.*lambda.^b + ...
                c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b)) -...
                (7493.*c1.*lambda.^(2.*b).*exp(-3.^(1./2).*((56145049.*lambda.^(2.*b))./(2313441.*(a + W.*c0.*lambda.^b +...
                c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b).^2) + rho.^2).^(1./2).*(W.*c0 + c3.*cco +...
                c1.*hbo + c2.*hbr).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr +...
                a./lambda.^b).^(1./2)).*(1./((56145049.*lambda.^(2.*b))./(2313441.*(a + W.*c0.*lambda.^b +...
                c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b).^2) + rho.^2).^(1./2) + 3.^(1./2).*(W.*c0 + c3.*cco +...
                c1.*hbo + c2.*hbr).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^(1./2)))./(1521.*((56145049.*lambda.^(2.*b))./(2313441.*(a + ...
                W.*c0.*lambda.^b + c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b).^2) + rho.^2).*(a + W.*c0.*lambda.^b + c3.*cco.*lambda.^b + ...
                c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b).^2) + (841389704314.*c1.*lambda.^(4.*b).*exp(-3.^(1./2).*((56145049.*lambda.^(2.*b))./(2313441.*(a +...
                W.*c0.*lambda.^b + c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b).^2) + rho.^2).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo +...
                c2.*hbr).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^(1./2)).*(1./((56145049.*lambda.^(2.*b))./(2313441.*(a +...
                W.*c0.*lambda.^b + c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b).^2) + rho.^2).^(1./2) + 3.^(1./2).*(W.*c0 + c3.*cco +...
                c1.*hbo + c2.*hbr).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^(1./2)))./(3518743761.*((56145049.*lambda.^(2.*b))./(2313441.*(a +...
                W.*c0.*lambda.^b + c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b).^2) + rho.^2).^2.*(a + W.*c0.*lambda.^b + c3.*cco.*lambda.^b +...
                c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b).^4)))./(25000.*pi.*((exp(-3.^(1./2).*(1./(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr +...
                a./lambda.^b).^2 + rho.^2).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr +...
                a./lambda.^b).^(1./2)).*(1./(1./(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^2 + rho.^2).^(1./2) + 3.^(1./2).*(W.*c0 + c3.*cco + c1.*hbo +...
                c2.*hbr).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^(1./2)))./((1./(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^2 +...
                rho.^2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b)) + (7493.*lambda.^b.*exp(-3.^(1./2).*((56145049.*lambda.^(2.*b))./(2313441.*(a +...
                W.*c0.*lambda.^b + c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b).^2) + rho.^2).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo +...
                c2.*hbr).^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^(1./2)).*(1./((56145049.*lambda.^(2.*b))./(2313441.*(a + W.*c0.*lambda.^b +...
                c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b).^2) + rho.^2).^(1./2) + 3.^(1./2).*(W.*c0 + c3.*cco + c1.*hbo + c2.*hbr).^(1./2).*(W.*c0 +...
                c3.*cco + c1.*hbo + c2.*hbr + a./lambda.^b).^(1./2)))./(1521.*((56145049.*lambda.^(2.*b))./(2313441.*(a + W.*c0.*lambda.^b + c3.*cco.*lambda.^b +...
                c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b).^2) + rho.^2).*(a + W.*c0.*lambda.^b + c3.*cco.*lambda.^b + c1.*hbo.*lambda.^b + c2.*hbr.*lambda.^b))).^2);
            
        end
        
    end
    
end
%
% syms c0 c1 c2 c3 hbo hbr W cco lambda rho a b r
% assume(c0,'real')
% assume(c1,'real')
% assume(c2,'real')
% assume(c3,'real')
% assume(hbo,'real')
% assume(hbr,'real')
% assume(W,'real')
% assume(cco,'real')
% assume(lambda,'real')
% assume(rho,'real')
% assume(a,'real')
% assume(b,'real')
% assume(r,'real')
%
% assume(c0,'positive')
% assume(c1,'positive')
% assume(c2,'positive')
% assume(c3,'positive')
% assume(hbo,'positive')
% assume(hbr,'positive')
% assume(W,'positive')
% assume(cco,'positive')
% assume(lambda,'positive')
% assume(rho,'positive')
% assume(a,'positive')
% assume(b,'positive')
% assume(r,'positive')
%
% mua = c0.*W+c1.*hbo+c2.*hbr+c3*cco;
% mus = a.*lambda.^(-b);
% mue = (3.*mua.*(mua + mus)).^(1/2); % effective attenuation coefficient
% D = 1./(3.*(mua+mus));
% z0 = 1./(mua+mus);
% zb = ((1+0.493)./(1-0.493)).*2.*D; %0.493 is Reff at n=1.4
% x0 = z0.^2 + rho.^2;
% x1 = (z0+2.*zb).^2 + rho.^2;
% refl = simplify((1/4*pi).*((z0.*(mue+1./sqrt(x0)).*exp(-mue.*sqrt(x0))./x0) +...
%     ((z0 + 2*zb).*(mue + 1./sqrt(x1)).*exp(-mue.*sqrt(x1))./x1)));
%
% s = simplify(r/(refl*100000));
%
% ds_dhbo=diff(s,hbo);
% ds_dhbr=diff(s,hbr);
% ds_dW=diff(s,W);
% ds_da=diff(s,a);
% ds_db=diff(s,b);
% ds_dcco=diff(s,cco);








